name1='小红'
name2='小明'
name3='小刚'
name4='小美'
print('第一种方法')
print(name1+'\n'+name2+'\n'+name3+'\n'+name4)
print('第二种方法')
print(name1,'\n',name2,'\n',name3,'\n',name4)
print('或')
print('',name1,'\n',name2,'\n',name3,'\n',name4)
print('第三种方法')
print(name1,name2,name3,name4,sep='\n')
print('第四种方法')
print("{}\n{}\n{}\n{}".format(name1,name2,name3,name4))
print('第五种方法')
print(name1+'''
'''+name2+'''
'''+name3+'''
'''+name4)

